language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

compiler: gcc-4.8

before_install:
  - sudo apt-get install -qq g++-4.8-multilib
  - sudo apt-get install -qq gcc-4.8-multilib

install:
 - export CC_host=gcc-4.8
 - export CXX_host=g++-4.8
 - unset CXX
 - unset CC
 - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
 - export PATH=`pwd`/depot_tools:"$PATH"
 - git apply 0000-hack-gclient-for-travis.patch
 - cd v8
 - git apply ../ndk14_5.7.patch
 - gclient sync
 - cd ..
 - wget http://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip
 - unzip -q android-ndk-r14b-linux-x86_64.zip
 - export ANDROID_NDK=${PWD}/android-ndk-r14b

script:
 - ./build_v8.sh -j4

after_success:
